// 🔹 Importerer globale CSS-stilark
import "./globals.css";

// 🔸 Importerer QuizProvider til at dele quiz-data globalt
import { QuizProvider } from './context/QuizContext';

// 🔸 Importerer skrifttyper fra Google Fonts via Next.js
import { Geist, Geist_Mono } from "next/font/google";

// 🔹 Initialiserer Geist Sans fonten med CSS-variabel
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

// 🔹 Initialiserer Geist Mono fonten med CSS-variabel
const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

// 🔸 Metadata bruges af Next.js til SEO og fanetitler
export const metadata = {
  title: 'Quiz App',
  description: 'Generated by Next.js',
};

// 🔸 RootLayout definerer den overordnede struktur for hele appen
export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        {/* 🔹 Gør quiz-data tilgængelig i hele appen via Context */}
        <QuizProvider>
          {children}
        </QuizProvider>
      </body>
    </html>
  );
}
